# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
alias dc="docker-compose"
alias dc_start="cd /c/Users/vyacheslav.vergeles/platform/laradock && docker-compose up -d apache2 redis"